---
- name: ansible playbook to test ansible vault
  hosts: all
  become: true
  vars_files:
    - vault-pass.yml
  tasks:
  - name: clone a git repo
    git:
      repo: https://sumant1902:{{ password }}@github.com/Sumant1902/vaults.git
      dest: /opt/ansadmin/test-vault
