---
- name: install apache2 on ubuntu server
  hosts: dbservers
  become: true
  tasks:
  - name: installing apache2 to ubuntu
    apt: 
      name: apache2
      state: present

  - name: start apache2 service
    service:
      name: apache2
      state: started
