---
- name: This playbook installs httpd
  hosts: webservers
  become: true
  tasks:
  - name: install package
    yum: 
      name: httpd
      state: installed
    notify: start httpd service

  handlers:   
  - name: start httpd service
    ansible.builtin.service:
      name: httpd
      state: started
      enabled: yes
