---
- name: setup tomcat
  hosts: all
  become: true
  tasks:
  - name: install java
    yum:
      name: java
      state: installed
    when: ansible_os_family == "RedHat"
  
  - name: java on Ubuntu
    apt:
      name: default-jdk
      state: present
    when: ansible_os_family == "Debian"

  - name: download tomcat packages
    get_url:
      url: https://downloads.apache.org/tomcat/tomcat-8/v8.5.69/bin/apache-tomcat-8.5.69.tar.gz.sha512
      dest: /opt

  - name: untar tomcat packages
    unarchive:
     src: /opt/apache-tomcat-8.5.69.tar.gz.sha512
     dest: /opt
     remote_src: yes

  - name: add execution permissions to startup.sh file
    file:
      path: /opt/apache-tomcat-8.5.69/bin/startup.sh
      mode: 0777

  - name: start tomcat services
    shell: nohup ./startup.sh
    args:
      chdir: /opt/apache-tomcat-8.5.69/bin
