---
- name: This playbook installs httpd
  hosts: all
  become: true
  vars:
    port: 8082      
  tasks:
  - name: install package
    yum:
      name: httpd
      state: installed
    when: ansible_os_family == "RedHat"
    notify: start httpd service
    
  - name: installing apache2 to ubuntu
    apt:
      name: apache2
      state: present
    when: ansible_os_family == "Debian"
    notify: start apache2 service

  - name: copy index.html
    copy:
      src: /opt/ansible/index.html
      dest: /var/www/html
      mode: 0666

  - name: change default listen port to {{ port }}
    ansible.builtin.lineinfile:
      path: /etc/httpd/conf/httpd.conf
      regexp: '^Listen '
      insertafter: '#Listen '
      line: Listen {{ port }}
    when: ansible_os_family == "RedHat"
    notify: restart httpd

  - name: change default listen port to {{ port }}
    ansible.builtin.lineinfile:
      path: /etc/apache2/ports.conf
      regexp: '^Listen '
      insertafter: '# /etc/apache2/sites-enabled/000-default.conf'
      line: Listen {{ port }}
    when: ansible_os_family == "Debian"
    notify: restart apache2

  handlers:    
  - name: start httpd service
    ansible.builtin.service:
      name: httpd
      state: started

  - name: start apache2 service
    service:
      name: apache2
      state: started

  - name: restart httpd
    service:
      name: httpd
      state: restarted

  - name: restart apache2
    service:
      name: apache2
      state: restarted
